# Generated by Django 5.1.7 on 2025-03-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistdocuments',
            name='experience_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychologistdocuments',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='psychologistdocuments',
            name='health_register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='psychologistdocuments',
            name='intervention_areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='psychologistdocuments',
            name='professional_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psychologistdocuments',
            name='specialties',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='psychologistdocuments',
            name='target_populations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='psychologistdocuments',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
